version: '3.7'
networks:
  backend:
    driver: '${NETWORKS_DRIVER}'
  frontend:
    driver: '${NETWORKS_DRIVER}'
volumes:
  percona:
    driver: '${VOLUMES_DRIVER}'
  adminer:
    driver: '${VOLUMES_DRIVER}'
services:
  php-fpm:
    build:
      context: ./etc
      dockerfile: ./php-fpm/Dockerfile
      args:
        - 'INSTALL_NODE=${INSTALL_NODE}'
        - 'INSTALL_POSTGRESQL=${INSTALL_POSTGRESQL}'
        - 'INSTALL_MYSQL=${INSTALL_MYSQL}'
        - 'INSTALL_XDEBUG=${INSTALL_XDEBUG}'
        - 'INSTALL_MONGODB=${INSTALL_MONGODB}'
        - 'INSTALL_FAKETIME=${INSTALL_FAKETIME}'
        - 'INSTALL_WKHTMLTOPDF=${INSTALL_WKHTMLTOPDF}'
        - 'PHP_VERSION=${PHP_VERSION}'
        - 'PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}'
        - 'PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}'
        - 'INSTALL_PRODUCTION=${INSTALL_PRODUCTION}'
    container_name: '${APP_NAME}_php_fpm'
    environment:
      - 'TZ=${TIMEZONE}'
    restart: on-failure
    volumes:
      - './etc/php-fpm/php.ini:/usr/local/etc/php/conf.d/php.ini:cached'
      - '${APP_PATH}/source:/var/www/html'
      - '${APP_PATH}/upload:/var/www/upload'
      - './etc/php-fpm/entrypoint.sh:/bin/entrypoint.sh'
    ports:
      - '${APACHE_WEBSOCKET_PORT}:6001'
    networks:
      - backend
  percona:
    container_name: '${APP_NAME}_percona'
    build:
      context: ./etc
      dockerfile: ./percona/Dockerfile
      args:
        - 'PERCONA_VERSION=${PERCONA_VERSION}'
    environment:
      - 'MYSQL_DATABASE=${PERCONA_DATABASE}'
      - 'MYSQL_USER=${PERCONA_USER}'
      - 'MYSQL_PASSWORD=${PERCONA_PASSWORD}'
      - 'MYSQL_ROOT_PASSWORD=${PERCONA_ROOT_PASSWORD}'
    volumes:
      - 'percona:/var/lib/mysql'
      - './etc/percona/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    ports:
      - '${PERCONA_PORT}:3306'
    networks:
      - backend
  apache2:
    container_name: '${APP_NAME}_apache2'
    build:
      context: ./etc
      dockerfile: ./apache2/Dockerfile
      args:
        - 'PHP_UPSTREAM_CONTAINER=${APACHE_PHP_UPSTREAM_CONTAINER}'
        - 'PHP_UPSTREAM_PORT=${APACHE_PHP_UPSTREAM_PORT}'
        - 'PHP_UPSTREAM_TIMEOUT=${APACHE_PHP_UPSTREAM_TIMEOUT}'
        - 'DOCUMENT_ROOT=${APACHE_DOCUMENT_ROOT}'
        - 'APACHE_INSTALL_HTTP2=${APACHE_INSTALL_HTTP2}'
    volumes:
      - '${APP_PATH}/source:/var/www/html'
      - '${APP_PATH}/upload:/var/www/upload'
      - '${APACHE_HOST_LOG_PATH}:/var/log/apache2'
    ports:
      - '${APACHE_HOST_HTTP_PORT}:80'
      - '${APACHE_HOST_HTTPS_PORT}:443'
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend
  redis:
    container_name: '${APP_NAME}_redis'
    environment:
      - 'TZ=${TIMEZONE}'
    image: redis
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - '${DATA_PATH_HOST}/redis:/data'
    restart: on-failure
    depends_on:
      - php-fpm
#      - apache2
    networks:
      - backend
  mailcatcher:
    image: schickling/mailcatcher
    container_name: '${APP_NAME}_mailcatcher'
    environment:
      - 'TZ=${TIMEZONE}'
    ports:
      - '${PORT_MAILCATCHER}:1080'
    depends_on:
      - php-fpm
#      - apache2
    networks:
      - backend
